using Microsoft.EntityFrameworkCore; using NeuroPulse.Api.Data; using NeuroPulse.Api.Models;
namespace NeuroPulse.Api.Services;
public class SessionService(AppDbContext db,HttpClient devices){
 public async Task<(RecordingSession? Session,string? Error)> Start(int participantId,int deviceId){var participant=await db.Participants.FindAsync(participantId);var device=await db.Devices.FindAsync(deviceId);if(participant is null)return(null,"Participant does not exist.");if(participant.Status!=ParticipantStatus.Active)return(null,"Participant is inactive.");if(device is null)return(null,"Device does not exist.");if(device.AssignedParticipantId!=participantId)return(null,"Device is not assigned to this participant.");if(device.ConnectionStatus!=ConnectionStatus.Connected)return(null,"Device is not connected.");if(device.BatteryPercentage<10)return(null,"Device battery must be at least 10%.");if(await db.Sessions.AnyAsync(x=>x.DeviceId==deviceId&&x.Status==SessionStatus.Recording))return(null,"Device already has an active recording.");
 try { var status=await devices.GetFromJsonAsync<DeviceStatus>($"api/devices/{device.SerialNumber}/status"); if(status is null||!status.Connected)return(null,"Simulator reports device unavailable."); } catch(Exception ex){return(null,$"Device status validation failed: {ex.Message}");}
 await Task.Delay(80); // widens the duplicate-submission race for exploration
 var session=new RecordingSession{ParticipantId=participantId,DeviceId=deviceId,StartedAt=DateTime.UtcNow,Status=SessionStatus.Recording,AverageSignal=Random.Shared.Next(55,90),SignalQuality=Random.Shared.NextDouble(),Notes="Recording initialising"};db.Sessions.Add(session);await db.SaveChangesAsync();return(session,null);}
 public async Task<(RecordingSession? Session,string? Error)> Stop(int id){var session=await db.Sessions.FindAsync(id);if(session is null)return(null,"Session does not exist.");if(session.Status!=SessionStatus.Recording)return(null,"Only a recording session may be stopped.");session.Status=SessionStatus.Completed;session.EndedAt=DateTime.UtcNow;await db.SaveChangesAsync();return(session,null);}
}
