using System.Text.Json.Serialization; using Microsoft.EntityFrameworkCore; using NeuroPulse.Api.Data; using NeuroPulse.Api.Models; using NeuroPulse.Api.Services;
var b=WebApplication.CreateBuilder(args);b.Services.AddDbContext<AppDbContext>(o=>o.UseNpgsql(b.Configuration.GetConnectionString("NeuroPulse")));b.Services.AddHttpClient<SessionService>(c=>c.BaseAddress=new Uri(b.Configuration["DeviceSimulatorUrl"]??"http://localhost:5100"));b.Services.AddHttpClient("sim",c=>c.BaseAddress=new Uri(b.Configuration["DeviceSimulatorUrl"]??"http://localhost:5100"));b.Services.ConfigureHttpJsonOptions(o=>o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));b.Services.AddEndpointsApiExplorer();b.Services.AddSwaggerGen();b.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));var app=b.Build();app.UseCors();app.UseSwagger();app.UseSwaggerUI();app.MapGet("/health",()=>Results.Ok(new{status="healthy",service="NeuroPulse.Api"}));
using(var scope=app.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<AppDbContext>();for(var i=0;i<10;i++){try{await db.Database.EnsureCreatedAsync();if(!await db.Participants.AnyAsync())await SeedData.Reset(db);break;}catch when(i<9){await Task.Delay(1500);}}}
var api=app.MapGroup("/api");
api.MapGet("/participants",async(string? search,ParticipantStatus? status,AppDbContext db)=>{var q=db.Participants.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(search)){await Task.Delay(120);q=q.Where(x=>(x.FirstName+" "+x.LastName).ToLower().Contains(search.ToLower())||x.Email.ToLower().Contains(search.ToLower()));}if(status.HasValue)q=q.Where(x=>x.Status==status);return await q.OrderBy(x=>x.Id).ToListAsync();});
api.MapGet("/participants/{id:int}",async(int id,AppDbContext db)=>await db.Participants.FindAsync(id) is {} p?Results.Ok(p):Results.NotFound());
api.MapPost("/participants",async(ParticipantRequest r,AppDbContext db)=>{var p=new Participant{FirstName=r.FirstName,LastName=r.LastName,Email=r.Email,DateOfBirth=r.DateOfBirth,Status=r.Status,CreatedAt=DateTime.UtcNow};db.Add(p);await db.SaveChangesAsync();return Results.Created($"/api/participants/{p.Id}",p);});
api.MapPut("/participants/{id:int}",async(int id,ParticipantRequest r,AppDbContext db)=>{var p=await db.Participants.FindAsync(id);if(p is null)return Results.NotFound();(p.FirstName,p.LastName,p.Email,p.DateOfBirth,p.Status)=(r.FirstName,r.LastName,r.Email,r.DateOfBirth,r.Status);await db.SaveChangesAsync();return Results.Ok(p);});
api.MapGet("/devices",async(ConnectionStatus? connection,bool? assigned,AppDbContext db)=>{var q=db.Devices.Include(x=>x.AssignedParticipant).AsNoTracking().AsQueryable();if(connection.HasValue)q=q.Where(x=>x.ConnectionStatus==connection);if(assigned.HasValue)q=q.Where(x=>(x.AssignedParticipantId!=null)==assigned);return await q.OrderBy(x=>x.Id).ToListAsync();});
api.MapGet("/devices/{id:int}",async(int id,AppDbContext db)=>await db.Devices.Include(x=>x.AssignedParticipant).FirstOrDefaultAsync(x=>x.Id==id) is {} d?Results.Ok(d):Results.NotFound());
api.MapPost("/devices",async(DeviceRequest r,AppDbContext db)=>{var d=new Device{SerialNumber=r.SerialNumber,Model=r.Model,FirmwareVersion=r.FirmwareVersion,BatteryPercentage=r.BatteryPercentage,ConnectionStatus=r.ConnectionStatus,LastSeenAt=DateTime.UtcNow};db.Add(d);await db.SaveChangesAsync();return Results.Created($"/api/devices/{d.Id}",d);});
api.MapPost("/devices/{id:int}/assign",async(int id,AssignmentRequest r,AppDbContext db)=>{var d=await db.Devices.FindAsync(id);if(d is null||await db.Participants.FindAsync(r.ParticipantId) is null)return Results.NotFound();d.AssignedParticipantId=r.ParticipantId;await db.SaveChangesAsync();return Results.Ok(d);});
api.MapPost("/devices/{id:int}/unassign",async(int id,AppDbContext db)=>{var d=await db.Devices.FindAsync(id);if(d is null)return Results.NotFound();d.AssignedParticipantId=null;await db.SaveChangesAsync();return Results.Ok(d);});
api.MapGet("/sessions",async(string? search,SessionStatus? status,AppDbContext db)=>{var q=db.Sessions.Include(x=>x.Participant).Include(x=>x.Device).AsNoTracking().AsQueryable();if(status.HasValue)q=q.Where(x=>x.Status==status);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>(x.Participant!.FirstName+" "+x.Participant.LastName).ToLower().Contains(search.ToLower())||x.Device!.SerialNumber.ToLower().Contains(search.ToLower()));return await q.OrderByDescending(x=>x.StartedAt).ToListAsync();});
api.MapGet("/sessions/{id:int}",async(int id,AppDbContext db)=>await db.Sessions.Include(x=>x.Participant).Include(x=>x.Device).FirstOrDefaultAsync(x=>x.Id==id) is {} s?Results.Ok(s):Results.NotFound());
api.MapPost("/sessions",async(SessionRequest r,SessionService svc)=>{var(s,e)=await svc.Start(r.ParticipantId,r.DeviceId);return e is null?Results.Created($"/api/sessions/{s!.Id}",s):Results.BadRequest(new{error=e});});api.MapPost("/sessions/{id:int}/stop",async(int id,SessionService svc)=>{var(s,e)=await svc.Stop(id);return e is null?Results.Ok(s):Results.BadRequest(new{error=e});});
api.MapGet("/sessions/{id:int}/telemetry",async(int id,AppDbContext db)=>await db.Telemetry.Where(x=>x.SessionId==id).OrderBy(x=>x.Timestamp).ToListAsync());
api.MapPost("/telemetry",async(TelemetryRequest r,AppDbContext db,IHttpClientFactory hf)=>{var config=await hf.CreateClient("sim").GetFromJsonAsync<Dictionary<string,object>>("api/training/config");if(config?.GetValueOrDefault("telemetryMode")?.ToString()?.Contains("High Volume")==true)await Task.Delay(45);var t=new TelemetryReading{DeviceId=r.DeviceId,SessionId=r.SessionId,Timestamp=r.Timestamp,Signal=r.Signal,Quality=r.Quality,BatteryPercentage=r.BatteryPercentage};db.Add(t);await db.SaveChangesAsync();return Results.Accepted($"/api/sessions/{r.SessionId}/telemetry",t);});
api.MapPost("/training/reset",async(AppDbContext db,IHttpClientFactory hf)=>{await SeedData.Reset(db);await hf.CreateClient("sim").PostAsync("api/training/scenarios/Normal",null);return Results.Ok(new{message="Training data restored"});});api.MapGet("/training/config",async(IHttpClientFactory hf)=>Results.Content(await hf.CreateClient("sim").GetStringAsync("api/training/config"),"application/json"));api.MapPost("/training/config",async(HttpRequest req,IHttpClientFactory hf)=>{var payload=await req.ReadFromJsonAsync<object>();var response=await hf.CreateClient("sim").PostAsJsonAsync("api/training/config",payload);return Results.Content(await response.Content.ReadAsStringAsync(),"application/json");});api.MapPost("/training/scenarios/{name}",async(string name,IHttpClientFactory hf)=>Results.Content(await (await hf.CreateClient("sim").PostAsync($"api/training/scenarios/{name}",null)).Content.ReadAsStringAsync(),"application/json"));app.Run();
